### ISSUE TITLE
Support for wsl

### ISSUE THREAD

**Issue by meijieru** [vimpostor/vim-lumen#11]
### Describe the bug

I am using the neovim within the wsl2 in win11.
The checkhealth reports the following
```
- OK Platform linux is supported
- OK Background job is running
- OK No job errors reported
```

### Expected behavior

It should be detected as windows and watch the event here.

### Debug output

```Text
{'platform': 'linux', 'job_state': 'run as PID 18145', 'job_errors': []}
```

**Comment by vimpostor** [comment]
> using wsl2 in win11
> ### Expected behavior
> It should be detected as windows and watch the event here.

Why do you expect that?

WSL2 is literally just a big Linux virtual machine, so it's equivalent to running Linux inside VirtualBox on Windows.
Let's not even pretend like that's not the case, just because the VM is a bit more neatly integrated.

Because of this, vim thinks it is running in Linux (`has('linux')` evaluates to true) - which is of course correct: it's running inside a Linux virtual machine after all.

There are some hacky workarounds to detect WSL, e.g. you could grep `uname -a` for WSL strings, but that is not an acceptable workaround: That would increase the startup time **for every user** of this plugin by a few ms, just to support this edge case of running Linux as a virtual machine inside Windows.

The best solution for this issue would be, if Microsoft continued their efforts to integrate WSL better into Windows, which in this case means implementing and shipping a custom XDG Desktop Portal implementation that acts as a proxy translating from the Linux `org.freedesktop.appearance` setting to the Windows `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme` setting. You could create such a feature request at https://github.com/Microsoft/WSL

I certainly think that would be a better solution, than asking every single project to implement an extra workaround just for WSL, because with that approach the workaround would have to be implemented only once: in the WSL XDG desktop portal.


If you find a way to detect WSL in vim without increasing startup time, I would reconsider this and implement a workaround, but until then I think the solution should be implemented on WSL's side.

Maybe I can also consider allowing the user to overwrite the detected platform, but the Windows support was really only intended for native Windows, not Linux inside Windows.

**Comment by vimpostor** [comment]
OK you can disregard my rant, according to https://github.com/vim/vim/pull/10464#issuecomment-1134606781 detecting WSL is as simple as checking an environment variable, which is basically no runtime overhead (compared to starting a new process for `uname`), so I have added a check to detect that.

Still it would be good, if you could test if it works now. As I said before, the Windows implementation was really only done with native Windows in mind, so there might be bugs when using it from WSL.

**Comment by meijieru** [comment]
Verified it correctly detect the platform in neovim in wsl2.
Though it don't work when changing the theme in the setting.
Any suggestion on how to debug it?

**Comment by meijieru** [comment]
checked the ocde and it seems that the `system` call [here](https://github.com/vimpostor/vim-lumen/blob/7b03332f602706b4d7e99a1cae35a13a9fa0ab15/autoload/lumen/platforms/windows.vim#L18) should be changed a bit.

**Comment by vimpostor** [comment]
> seems that the system call [here](https://github.com/vimpostor/vim-lumen/blob/7b03332f602706b4d7e99a1cae35a13a9fa0ab15/autoload/lumen/platforms/windows.vim#L18) should be changed a bit.

Why? I thought you could call Windows programs like `reg` from inside WSL2 and it just works?
If you find out what is wrong, feel free to make a PR.

As for debugging, all errors of the job are logged in `echom lumen#debug#info()`.

**Comment by vimpostor** [comment]
Can you test again? It should work with WSL now.

**Comment by meijieru** [comment]
Thanks!
I just checked, the only problem is that we should use `powershell.exe` instead of `PowerShell.exe` under WSL.

**Comment by vimpostor** [comment]
> we should use powershell.exe instead of PowerShell.exe

I don't see the reason for this, NTFS is case-insensitive after all. If I run `which PowerShell.exe` in WSL, it resolves the path correctly.
I changed it to lowercase anyway now, can you confirm it works now for you? Otherwise please post the output of `echom lumen#debug#info()`.

**Comment by meijieru** [comment]
It works now! Thx!

**Comment by arpanetus** [comment]
This is an awesome plugin, I'm so happy. Thanks a lot!!!!
